public enum tokenType{
  PROGRAM_TKN,BLOCK_TKN,IDEN_TKN,STATEMENT_TKN,
    IF_STATEMENT_TKN,WHILE_STATEMENT_TKN,ASSIGNMENT_STATEMENT_TKN,PRINT_STATEMENT_TKN,REPEAT_STATEMENT_TKN,
    BOOLEAN_EXPR_TKN,
    ASSIGNMENT_OP_TKN,ARITH_EXPR_TKN,
    RELATIVE_OP_TKN,
    ARITH_OP_TKN,
    LITERAL_INTEGAR_TKN
    
    
}